const L = {
  zh: {
    main_title: "📡 *Crypto/Stock Monitor*\n\n💰 查价格 · 🚨 设提醒 · 📊 看行情 · 🔥 热门 · 🌐 数据 · 📡 新闻\n\n全部免费使用 👇",
    btn_prices: "💰 价格查询", btn_alerts: "🚨 价格提醒", btn_overview: "📊 市场概览", btn_trending: "🔥 热门币种", btn_global: "🌐 全球数据", btn_news: "📡 新闻订阅", btn_ad: "📢 广告合作",
    lang_btn: "🌐 English", lang_done: "已切换为 English",
    welcome: "👋 欢迎使用 *Crypto/Stock Monitor*！",
    price_title: "💰 *选择要查询的品种*", stock_title: "📈 *美股行情*\n点击查看：", btn_stock: "📈 美股",
    refresh: "🔄 刷新", back: "◀ 返回", custom: "🔍 自定义",
    fetching: "🔍 查询 ", not_found: "❌ 未找到 ",
    label_1h: "1h: ", label_24h: "24h: ", label_7d: "7d: ",
    label_cap: "🏢 市值: ", label_vol: "💹 24h量: ", label_supply: "🔄 流通: ", label_ath: "🏆 历史最高: ",
    prompt_symbol: "🔍 请输入股票或加密货币代码（如 BTC、AAPL、TSLA）：",
    ov_crypto: "📊 *加密货币概览*", ov_stock: "📈 *美股概览*", btn_ov_stock: "📈 美股", btn_ov_crypto: "₿ 加密",
    trending_title: "🔥 *CoinGecko 热门币种*", trending_empty: "暂时无法获取热门数据",
    global_title: "🌐 *市场全局数据*", global_cap: "总市值: ", global_vol: "24h交易量: ", global_btc: "BTC占比: ", global_eth: "ETH占比: ", global_coins: "加密货币总数: ",
    alert_title: "🚨 *价格提醒*", alert_desc: "价格突破或跌破时自动推送通知。",
    my_alerts: "📋 我的提醒", new_alert: "➕ 新建提醒", no_alerts: "📭 暂无价格提醒", alert_list: "🚨 *价格提醒*", alert_created: "✅ *提醒已设置！*", alert_del: "✅ 已删除",
    above: "📈 高于", below: "📉 低于", again: "➕ 再建一个",
    prompt_price: "请输入目标价格（美元）：", prompt_dir: "请选择触发方向：", prompt_asym: "🔍 请输入品种代码（如 BTC、AAPL）：", sel_sym: "选择品种：", sel_stock: "📈 选择美股：",
    news_title: "📡 *新闻源*\n选择分类浏览 + 订阅：", add_feed: "➕ 添加自定义源",
    prompt_feed: "📡 请输入 RSS 链接：\n（如 https://example.com/rss）", feed_ok: "✅ *已添加订阅！*",
    ad_title: "📢 *广告合作*", ad_body: "你的项目、交易所或产品想在 bot 上投放广告？\n\n📊 覆盖用户：加密货币 + 美股交易者\n📈 推广形式：置顶消息 / 价格卡片冠名\n\n联系 Telegram: pincess_aoao",
    loading: "请稍候...", err_fetch: "❌ 获取失败", err_q: "❌ 查询失败", err_price: "❌ 无效价格", err_url: "❌ 无效 URL", err_sub: "❌ 添加失败", del_ok: "✅ 已删除",
    nft: "🖼️ NFT",
    btn_cats: "🏷️ 分类", cat_title: "🏷️ *分类浏览*", fng: "😱 恐惧贪婪", fng_value: "当前值: ", fng_class: "状态: ",
    exchanges: "🏛️ 交易所", daly: "📅 每日简报", daly_on: "📅 简报: ✅", daly_off: "📅 简报: ❌",
  },
  en: {
    main_title: "📡 *Crypto/Stock Monitor*\n\n💰 Prices · 🚨 Alerts · 📊 Overview · 🔥 Trending · 🌐 Market · 📡 News\n\nCompletely free 👇",
    btn_prices: "💰 Prices", btn_alerts: "🚨 Alerts", btn_overview: "📊 Overview", btn_trending: "🔥 Trending", btn_global: "🌐 Market Data", btn_news: "📡 News", btn_ad: "📢 Advertise",
    lang_btn: "🌐 中文", lang_done: "Switched to 中文",
    welcome: "👋 Welcome to *Crypto/Stock Monitor*!",
    price_title: "💰 *Select asset*", stock_title: "📈 *US Stocks*\nTap to view:", btn_stock: "📈 US Stocks",
    refresh: "🔄 Refresh", back: "◀ Back", custom: "🔍 Custom",
    fetching: "🔍 Fetching ", not_found: "❌ Not found: ",
    label_1h: "1h: ", label_24h: "24h: ", label_7d: "7d: ",
    label_cap: "🏢 Cap: ", label_vol: "💹 Vol(24h): ", label_supply: "🔄 Supply: ", label_ath: "🏆 ATH: ",
    prompt_symbol: "🔍 Enter symbol (e.g. BTC, AAPL, TSLA):",
    ov_crypto: "📊 *Crypto Overview*", ov_stock: "📈 *Stock Overview*", btn_ov_stock: "📈 Stocks", btn_ov_crypto: "₿ Crypto",
    trending_title: "🔥 *Trending on CoinGecko*", trending_empty: "Can't fetch trending now",
    global_title: "🌐 *Global Market Data*", global_cap: "Total Cap: ", global_vol: "24h Vol: ", global_btc: "BTC Dom: ", global_eth: "ETH Dom: ", global_coins: "Cryptocurrencies: ",
    alert_title: "🚨 *Price Alerts*", alert_desc: "Get notified when price breaks your target.",
    my_alerts: "📋 My Alerts", new_alert: "➕ New Alert", no_alerts: "📭 No alerts yet", alert_list: "🚨 *Price Alerts*", alert_created: "✅ *Alert created!*", alert_del: "✅ Deleted",
    above: "📈 Above", below: "📉 Below", again: "➕ Create another",
    prompt_price: "Enter target price (USD):", prompt_dir: "Select direction:", prompt_asym: "🔍 Enter symbol (e.g. BTC, AAPL):", sel_sym: "Select asset:", sel_stock: "📈 Select US stock:",
    news_title: "📡 *News Sources*\nBrowse categories:", add_feed: "➕ Add custom feed",
    prompt_feed: "📡 Enter RSS URL:\n(e.g. https://example.com/rss)", feed_ok: "✅ *Subscribed!*",
    ad_title: "📢 *Advertise*", ad_body: "Want to advertise your project or exchange?\n\n📊 Audience: Crypto + Stock traders\n📈 Formats: Pinned / Card sponsorship\n\nContact: @pincess_aoao",
    loading: "Loading...", err_fetch: "❌ Failed", err_q: "❌ Query failed", err_price: "❌ Invalid price", err_url: "❌ Invalid URL", err_sub: "❌ Subscription failed", del_ok: "✅ Deleted",
    nft: "🖼️ NFT",
    btn_cats: "🏷️ Categories", cat_title: "🏷️ *Browse Categories*", fng: "😱 Fear & Greed", fng_value: "Value: ", fng_class: "Status: ",
    exchanges: "🏛️ Exchanges", daly: "📅 Daily Brief", daly_on: "📅 Brief: ✅", daly_off: "📅 Brief: ❌",
  }
};
function t(lang, key) { return (L[lang]||L.zh)[key]||L.zh[key]||key; }
module.exports = { t };

